Name=zero-lliurex-ai-models
Name[es]=Instalador de modelos IA
Name[ca@valencia]=Instal·lador de models IA
Name[qcv]=Instal·lador de models IA
Name[ca_ES]=Instal·lador de models IA
Comment=AI models installer
Comment[es]=Instalador de modelos IA
Comment[ca@valencia]=Instal·lador de models IA
Comment[qcv]=Instal·lador de models IA
Comment[ca_ES]=Instal·lador de models IA
Icon=zero-lliurex-ai-models
Category=Software
ScriptPath=zero-lliurex-ai-models.zmd
Groups=sudo;admins;teachers
Using=pkexec
#Service=True
#Modal=True
Show=True